# Generated by Django 4.1 on 2023-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.TextField(db_column='Name', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flyght_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Flight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duration', models.BigIntegerField(db_column='Duration')),
                ('monday', models.TimeField(blank=True, db_column='Monday', null=True)),
                ('tuesday', models.TimeField(blank=True, db_column='Tuesday', null=True)),
                ('wednesday', models.TimeField(blank=True, db_column='Wednesday', null=True)),
                ('thursday', models.TimeField(blank=True, db_column='Thursday', null=True)),
                ('friday', models.TimeField(blank=True, db_column='Friday', null=True)),
                ('saturday', models.TimeField(blank=True, db_column='Saturday', null=True)),
                ('sunday', models.TimeField(blank=True, db_column='Sunday', null=True)),
            ],
            options={
                'db_table': 'Schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pasport_id', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('seat_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.TextField(primary_key=True, serialize=False)),
                ('assembly_date', models.DateTimeField()),
                ('type', models.TextField()),
                ('seat_amount', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
    ]
